#' @name oxford_error
#' @title Process Errors from the Oxford Dictionaries API
#' 
#' @description Provides a consistent interface for managing errors from the 
#'   Oxford Dictionaries API
#'   
#' @param response An object of class \code{response} as generated by a 
#'   \code{\link[httr]{GET}} call.
#'
#' @export

oxford_error <- function(response){
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = response,
                          classes = "response",
                          add = coll)
  
  checkmate::reportAssertions(coll)
  
  if (response[["status_code"]] != 200)
    coll$push(paste0(response[["status_code"]], 
                     ": ", 
                     as.character(response)))
  
  checkmate::reportAssertions(coll)
}